### ISSUE TITLE
how to test it on emulator?

### ISSUE THREAD

**Issue by milon27** [dipeshkoirala21/rn-geofence#1]

**Comment by dipeshkoirala21** [comment]
To Test on Emulator, tweak these parameters. Add latitude and longitude of your location in the below code, and  on emulator, you can manually add latitude and longitude from the settings. first try adding location farther away from 500m radius and then add the location within 500m. You will get the notification stating that the user has entered the geofence area. 
``` 
const geofence = {
  latitude: 22.706141,
  longitude: 100.384468,
  radius: 500, // 500 meters
};
```
